image: node:14

stages:
  - prepare
  - build
  - measure
  - document
  - test
  - secure
  - deploy
  - pages
  - update_document

variables:
  SONAR_SCANNER_OPTS: "-Dsonar.projectKey=my-node-app -Dsonar.sources=src -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${SONAR_TOKEN}"

before_script:
  - npm install

prepare:
  stage: prepare
  script:
    - echo "Preparing the environment..."

build:
  stage: build
  script:
    - npm run build

measure:
  stage: measure
  script:
    - apt-get update
    - apt-get install -y openjdk-11-jre
    - npm install -g sonarqube-scanner
    - sonar-scanner

document:
  stage: document
  script:
    - npm run generate-docs
    - echo "Documentation generated."

test:
  stage: test
  script:
    - npm test

secure:
  stage: secure
  script:
    - npm audit

deploy:
  stage: deploy
  script:
    - npm run deploy

pages:
  stage: pages
  script:
    - npm run generate-docs
    - mv docs public
  artifacts:
    paths:
      - public

update_document:
  stage: update_document
  script:
    - npm run update-docs
    - git config --global user.name "gitlab-ci"
    - git config --global user.email "gitlab-ci@example.com"
    - git add .
    - git commit -m "Update documentation"
    - git push
