image: node:14

stages:
  - prepare
  - build
  - test
  - measure
  - deploy

variables:
  SONAR_SCANNER_OPTS: "-Dsonar.projectKey=my-node-app -Dsonar.sources=src -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${SONAR_TOKEN}"

before_script:
  - npm install

prepare:
  stage: prepare
  script:
    - echo "Preparing the environment..."
  tags:
    - shell
    - local

build:
  stage: build
  script:
    - echo "Building the project..."
    - npm run build
  tags:
    - shell
    - local

test:
  stage: test
  script:
    - npm test
  tags:
    - shell
    - local

measure:
  stage: measure
  script:
    - apt-get update
    - apt-get install -y openjdk-11-jre
    - npm install -g sonarqube-scanner
    - sonar-scanner
  tags:
    - shell
    - local

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
  tags:
    - shell
    - local
